
Monster_Damage:
  RANK1_MAX_DMG: 20
  RANK2_MAX_DMG: 50
  RANK3_MAX_DMG: 80
  RANK4_MAX_DMG: 110
  RANK5_MAX_DMG: 140
  RANK6_MAX_DMG: 170
  RANK7_MAX_DMG: 200
  RANK8_MAX_DMG: 230
  RANK9_MAX_DMG: 260
  RANK10_MAX_DMG: 300

Monster_Defense:
  RANK1_DEFENSE: 3
  RANK2_DEFENSE: 4
  RANK3_DEFENSE: 6
  RANK4_DEFENSE: 9
  RANK5_DEFENSE: 12
  RANK6_DEFENSE: 15
  RANK7_DEFENSE: 18
  RANK8_DEFENSE: 21
  RANK9_DEFENSE: 30
  RANK10_DEFENSE: 45

Monster_HP:
  RANK1_MAX_HP: 50
  RANK2_MAX_HP: 75
  RANK3_MAX_HP: 125
  RANK4_MAX_HP: 175
  RANK5_MAX_HP: 225
  RANK6_MAX_HP: 275
  RANK7_MAX_HP: 325
  RANK8_MAX_HP: 375
  RANK9_MAX_HP: 600
  RANK10_MAX_HP: 16000

Monster_Initiative:
  RANK1_INITIATIVE: 6
  RANK2_INITIATIVE: 8
  RANK3_INITIATIVE: 10
  RANK4_INITIATIVE: 12
  RANK5_INITIATIVE: 14
  RANK6_INITIATIVE: 16
  RANK7_INITIATIVE: 18
  RANK8_INITIATIVE: 20
  RANK9_INITIATIVE: 22
  RANK10_INITIATIVE: 24

Monster_Crit:  # Calculated in items by 1 to n ratio
  RANK1_CRIT: 10
  RANK2_CRIT: 10
  RANK3_CRIT: 10
  RANK4_CRIT: 10
  RANK5_CRIT: 9
  RANK6_CRIT: 9
  RANK7_CRIT: 9
  RANK8_CRIT: 8
  RANK9_CRIT: 8
  RANK10_CRIT: 8

Monster_Crit_Multiplier:
  RANK1_CRIT_MULTI: 1.1
  RANK2_CRIT_MULTI: 1.1
  RANK3_CRIT_MULTI: 1.2
  RANK4_CRIT_MULTI: 1.2
  RANK5_CRIT_MULTI: 1.3
  RANK6_CRIT_MULTI: 1.3
  RANK7_CRIT_MULTI: 1.4
  RANK8_CRIT_MULTI: 1.4
  RANK9_CRIT_MULTI: 1.5
  RANK10_CRIT_MULTI: 1.5

Monster_Item_Drop_Chance:  # Calculated in items by 1 to n ratio
  RANK1_DROP_CHANCE: 4
  RANK2_DROP_CHANCE: 4
  RANK3_DROP_CHANCE: 4
  RANK4_DROP_CHANCE: 5
  RANK5_DROP_CHANCE: 5
  RANK6_DROP_CHANCE: 5
  RANK7_DROP_CHANCE: 5
  RANK8_DROP_CHANCE: 6
  RANK9_DROP_CHANCE: 8
  RANK10_DROP_CHANCE: 1

Monster_XP:
  RANK1_XP: 75
  RANK2_XP: 150
  RANK3_XP: 200
  RANK4_XP: 250
  RANK5_XP: 300
  RANK6_XP: 350
  RANK7_XP: 400
  RANK8_XP: 450
  RANK9_XP: 750
  RANK10_XP: 15000

Monster_Gold:
  RANK1_GOLD: 10
  RANK2_GOLD: 20
  RANK3_GOLD: 30
  RANK4_GOLD: 40
  RANK5_GOLD: 50
  RANK6_GOLD: 60
  RANK7_GOLD: 70
  RANK8_GOLD: 80
  RANK9_GOLD: 90
  RANK10_GOLD: 1000