
Padded Armor:
  rank: 1
  bonus_defense: 5
  bonus_hp: 20

Leather Armor:
  rank: 1
  bonus_defense: 10
  bonus_hp: 40

Studded Leather Armor:
  rank: 1
  bonus_defense: 15
  bonus_hp: 70

Hide Armor:
  rank: 2
  bonus_defense: 20
  bonus_hp: 100

Chain Shirt:
  rank: 2
  bonus_defense: 25
  bonus_hp: 130

Scale Mail:
  rank: 2
  bonus_defense: 30
  bonus_hp: 160

Breastplate:
  rank: 3
  bonus_defense: 35
  bonus_hp: 190

Halfplate Armor:
  rank: 3
  bonus_defense: 40
  bonus_hp: 220

Ring Mail:
  rank: 3
  bonus_defense: 45
  bonus_hp: 250

Chain Mail:
  rank: 4
  bonus_defense: 50
  bonus_hp: 280

Splint Armor:
  rank: 4
  bonus_defense: 55
  bonus_hp: 310

Plate Mail:
  rank: 4
  bonus_defense: 60
  bonus_hp: 340