Club:
  rank: 1
  bonus_atk: 15
  bonus_def: 5

Handaxe:
  rank: 1
  bonus_atk: 22
  bonus_def: 2

Spear:
  rank: 1
  bonus_atk: 18
  bonus_def: 6

Rapier:
  rank: 2
  bonus_atk: 30
  bonus_def: 7

Longsword:
  rank: 2
  bonus_atk: 28
  bonus_def: 7

Battleaxe:
  rank: 3
  bonus_atk: 42
  bonus_def: 10

Greatsword:
  rank: 3
  bonus_atk: 50
  bonus_def: 10

